//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace the_website_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        public int ID { get; set; }
        public Nullable<int> SubjID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
