//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace the_website_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturesTable
    {
        public int ID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StaffMemeberID1 { get; set; }
        public Nullable<int> StaffMemeberID2 { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual StaffMembers StaffMembers { get; set; }
        public virtual StaffMembers StaffMembers1 { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
